trigger:
- master

variables:
  azureSubscription: 'dfe5229f-1fa1-4e86-ace2-719be2561fc4'
  webAppName: 'flatris'
  resourceGroupName: 'VisualStudioOnline-2F36836A663241BB8262844FEB13929F'
  environmentName: 'flatris'
  vmImageName: Default
  buildFolder: 'dist'             

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      name: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'        
      displayName: 'Use Node.js 16.x'

    - script: |
        yarn install --frozen-lockfile
        yarn build
      displayName: 'Install dependencies and build locally'

    - task: ArchiveFiles@2
      displayName: 'Archive build output'
      inputs:
        rootFolderOrFile: '$(buildFolder)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy Job
    environment: $(environmentName)
    pool:
      name: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: 'Disable server-side build'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              resourceGroupName: $(resourceGroupName)
              appSettings: |
                [
                  { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "false" }
                ]

          - task: AzureWebApp@1
            displayName: 'Deploy pre-built artifact'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
